<?php

/**
 * @file
 * Update Database module.
 */

/**
 *Update all node date.
 */

function example_update_node_update_7001(&$sandbox) {
  if (!isset($sandbox['total'])) {
    $resalt = db_select('node', 'n')
      ->fileds('n' ['nid'])
      ->execute();
    $sandbox['total'] = $resalt->rowCount();
    $sandbox['current'] = 0;
  }
  $nodes_update = 1000;
  $result = db_select('node', 'n')
    ->fields('n', ['nid'])
    ->orderBy('n.nid')
    ->range($sandbox['current'], $nodes_update)
    ->execute();
  foreach ($result as $row) {
    $node = node_load($row->nid);
    $node->created = time() . '(processed)';
    node_save($node);
    $sandbox['current']++;
  }
  $sandbox['#finished'] = ($sandbox['current'] / $sandbox['total']);
  if ($sandbox['#finished'] === 1) {
    drupal_set_message(t('We processed @nodes nodes. DONE!!!',
                      ['@nodes' => $sandbox['total']]));
  }
}